MODEL:
  TYPE: cross-scale
  NAME: cros_small_patch4_linear_group_224
  DROP_PATH_RATE: 0.2
  # delete this line if you run the code on ImageNet-1K
  NUM_CLASSES: 200
  CROS:
    EMBED_DIM: 64
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 2, 4, 8, 16 ]
    GROUP_SIZE: [ 4, 4, 14, 7]
    PATCH_SIZE: [4, 8, 16, 32]
    MERGE_SIZE: [[2, 4], [2,4], [2, 4]]